### ISSUE TITLE
做成lceda插件

### ISSUE THREAD

**Issue by easyeda2021** [Jiangshan00001/easyeda_to_pads#1]
楼主，你的代码是否可以做成lceda的插件？让用户自己安装后，自己打开库然后到处pads格式。需要哪个到出哪个。
例子 【插件】立创EDA第三方插件汇总    http://club.szlcsc.com/article/details_49807_1.html
https://github.com/xsrf/easyeda-extension-example

**Comment by Jiangshan00001** [comment]
@EasyEDA2021 理论上没问题。
不过现在这个是python的脚本。我看easyeda插件需要js才行？
是否有支持python的插件编写方式？

**Comment by easyeda2021** [comment]
> 
> 
> @EasyEDA2021 理论上没问题。
> 不过现在这个是python的脚本。我看easyeda插件需要js才行？
> 是否有支持python的插件编写方式？

不支持。。。因为lceda就是js写的

**Comment by Jiangshan00001** [comment]
我添加了源代码在src目录下
是py的
